### ISSUE TITLE
Status command feedback message error

### ISSUE THREAD

**Issue by LingZiyann** [AY2425S1-CS2103T-F10-4/tp#104]
When using status command wrongly, the feedback message given is 
"Invalid command format! 
status: Edits the application status of the company identified by the index number used in the last company listing. Existing application status will be overwritten by the input.
Parameters: INDEX (must be a positive integer) as/ [STATUS]
Example: status 1 status/ Ongoing"
However, i think "status 1 status/ Ongoing" is wrong and should be "status 1 as/Ongoing" instead

**Comment by vinceg4** [comment]
has been fixed
