### ISSUE TITLE
Tag command works even with no underscore

### ISSUE THREAD

**Issue by rynlwhh** [AY2425S1-CS2103T-F10-4/tp#109]
<img width="706" alt="Screenshot 2024-11-05 at 7 03 26 PM" src="https://github.com/user-attachments/assets/28531450-3213-46b9-b5a9-e2bf624a6a3c">

The tag underscore still works even though in the UG it states need to put underscore, so either show invalid command when underscore is not present or allow it and change the UG

**Comment by LingZiyann** [comment]
This is actually the expected behavior noted at the UG 
"Note: If no valid value is provided, the tag will be displayed as it is without special handling. For example, t/randomtag will appear as "randomtag"."
But i think i'll update the UG to clarify this and make it more obvious
