### ISSUE TITLE
Bookmark feedback does not show the bookmark message

### ISSUE THREAD

**Issue by tckeong** [AY2425S1-CS2103T-F10-4/tp#113]
After bookmark a company, it does not show the bookmark data in the success message

**Comment by vinceg4** [comment]
I have added the bookmark value to show on the UI so now when bookmark is used, it shows something like this:
<img width="926" alt="image" src="https://github.com/user-attachments/assets/ef9fc3d4-1546-4fcb-a220-5bd2489eceff">
However, this might confuse people as the bookmark value shown is initially false (as it was not bookmarked). I will update the UG to point it out to users.
