### ISSUE TITLE
Inaccurate UI error message

### ISSUE THREAD

**Issue by rynlwhh** [AY2425S1-CS2103T-F10-4/tp#116]
<img width="733" alt="Screenshot 2024-11-05 at 8 53 24 PM" src="https://github.com/user-attachments/assets/9be626b3-e977-4073-bc99-75ee5a3d194e">

UI message is inaccurate as the tag name is alphanumeric just that it was not the right tag name. Error message should be different.

**Comment by LingZiyann** [comment]
This is also a expected behavior as the tag given is not a valid tag, so it will try to display "sal_HIGH" as it is, and the underscore gives an error. But i will update the UG to make it clearer
