### ISSUE TITLE
[PE-D][Tester D] Different error messages for out of bounds (`remark`)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F10-4/tp#160]
Similar to #5 on `edit`, `remark` has the same issue.

![image.png](https://raw.githubusercontent.com/riccoljy/ped/main/files/f991577e-154f-4ba0-b74d-5e68da088ca7.png)

![image.png](https://raw.githubusercontent.com/riccoljy/ped/main/files/9ff22f54-4f22-4e17-af48-5055b03396ea.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: riccoljy/ped#6

**Comment by vinceg4** [comment]
mentioned in UG that INDEX needs to be positive so anyth else is an invalid command
