### ISSUE TITLE
[PE-D][Tester A] Add format's remark type

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F10-4/tp#168]
If in add command, remark can be an empty string (which defaults to None), why not make it optional like tag? Currently it is compulsory which requires users to type an additional r/.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: estellelim/ped#2

**Comment by vinceg4** [comment]
Can be included in planned enhancements
