### ISSUE TITLE
[PE-D][Tester C] UG image not complete

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F10-4/tp#176]
![image.png](https://raw.githubusercontent.com/raageth/ped/main/files/fd7424e5-7cd8-4a4c-b898-ffafe6f9093e.png)
Message shown to the user is cut off

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: raageth/ped#2

**Comment by LingZiyann** [comment]
what

**Comment by vinceg4** [comment]
going to close as this does not seem like a bug.
