### ISSUE TITLE
[PE-D][Tester A] Edit command format incorrect in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F10-4/tp#183]
The format in UG for Edit does not have ... for TAG
![image.png](https://raw.githubusercontent.com/estellelim/ped/main/files/ebd0218e-fcf8-4266-b23a-63c12908b6cd.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: estellelim/ped#5

**Comment by LingZiyann** [comment]
huh
