### ISSUE TITLE
[PE-D][Tester D] Hyperlinks not changed in DG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F10-4/tp#184]
Java file hyperlink points to AB3 one
![image.png](https://raw.githubusercontent.com/riccoljy/ped/main/files/c4b84123-7d6d-4e37-beb1-5067ac0ed15c.png)

-------------
Labels: `severity.High` `type.DocumentationBug`
original: riccoljy/ped#16

**Comment by LingZiyann** [comment]
i cant see which link tho
