### ISSUE TITLE
[PE-D][Tester C] Remark can accept the value of None

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F10-4/tp#192]
![image.png](https://raw.githubusercontent.com/raageth/ped/main/files/c0df068b-0dc3-4d9e-bc14-0d19b5d50760.png)
`remark 1 r/None` is possible. `remark 1 r/` produces the same result.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: raageth/ped#6

**Comment by vinceg4** [comment]
not sure if this constitutes as a bug because it is really js adding "None" as a remark. Perhaps will mention in UG that the default remark value will be "None".
