### ISSUE TITLE
[PE-D][Tester C] Missing info in DG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F10-4/tp#211]
![image.png](https://raw.githubusercontent.com/raageth/ped/main/files/84ab032e-7e86-4892-9d45-bbbce9c6d7e9.png)
No text under undo/redo feature

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: raageth/ped#10

**Comment by LingZiyann** [comment]
I propose to just remove it

**Comment by vinceg4** [comment]
fixed
